# Generated by Django 4.2.5 on 2023-11-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornada_milhas', '0002_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depoimento',
            name='foto',
            field=models.ImageField(upload_to='depoimentos/'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='foto_1',
            field=models.ImageField(upload_to='destinos/'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='foto_2',
            field=models.ImageField(upload_to='destinos/'),
        ),
    ]
